@startuml

title Programm Tracker Algorithm

start

:Выбор в меню \n1, 2, 3, 4, 5 or 6;

while (exit?) is (No)

  if (1) then (yes)
    :if 1
      Добавление
      новой заявки;
    :Введите
      имя заявки:;
    :Введите
      описание
      заявки;

  elseif (2) then (yes)
    :If 2
      Редактирования 
      заявки.;
    :Введите номер заявки 
      для редактирования:;
    :Введите новое 
      имя заявки:;
    :Введите 
      новое
      описание 
      заявки:;

  elseif (3) then (yes)
    :If 3
      Удаление 
      заявки.;
    :Введите номер заявки 
      для удаления:;

  elseif (4) then (yes)
    :If 4
      Отображение 
      списка 
      всех заявок.;

  elseif (5) then (yes)
    :If 5
      Отображения заявок 
      с условием фильтра.;

  elseif (6) then (yes)
    :If 6
      Добавлять к заявке 
      комментарий.;
    :Введите 
      комментарий 
      к заявке:;

  elseif (Number out of range) then (yes)
    :Print a number in range;

  else 
    :Print right number;

  endif

endwhile (Yes)

stop

@enduml

Choose in menu:
1. Добавление новой заявки
2. Редактирования заявки.
3. Удаления заявки.
4. Отображение списка всех заявок.
5. Отображения заявок с условием фильтра.
6. Добавлять к заявки комментарий.


